(function initSecurity() {
    document.addEventListener('DOMContentLoaded', () => {
        
        const i18n = {
            es: {
                navHome: "Volver al inicio",
                pageTitle: "Nota Técnica - Seguridad",
                docTitle: "NOTA TÉCNICA",
                docSubtitle: "Confidencialidad y no almacenamiento de datos personales",
                metaProduct: "Producto: Client Form",
                metaVersion: "Versión: 2026",
                metaAuthor: "Autor: Guilhem Normand",
                
                h1Title: "1. Resumen ejecutivo",
                h1P1: "Esta nota responde a la pregunta planteada: «¿Cómo garantiza la aplicación que la información del cliente no queda guardada en ningún sitio?»",
                h1P2: "La respuesta es estructural: la aplicación actúa como un espejo digital. Los datos que el cliente teclea en su dispositivo se reflejan en tiempo real en la pantalla del asesor, sin pasar por ningún servidor ni base de datos. En cuanto se cierra la sesión, los datos desaparecen.",
                
                h2Title: "2. Arquitectura: cómo funciona el espejo",
                h2P1: "La transmisión de datos se realiza mediante WebRTC (Web Real-Time Communication), una tecnología de conexión directa entre dispositivos estandarizada por el W3C e implementada de forma nativa en todos los navegadores modernos.",
                diagClient: "Dispositivo cliente",
                diagClientSub: "Introduce sus datos",
                diagChannel: "Canal WebRTC P2P",
                diagChannelSub: "Cifrado extremo a extremo",
                diagAgent: "Pantalla asesor",
                diagAgentSub: "Muestra datos en tiempo real",
                h2P2: "Ningún servidor intermedio toca los datos personales del cliente. El servidor de señalización solo actúa como \"directorio telefónico\" para establecer el canal; una vez abierto, desaparece de la ecuación.",
                
                h3Title: "3. ¿Qué datos se almacenan y cuáles no?",
                thData: "Dato",
                thStored: "¿Se almacena?",
                td1Data: "Dirección / CP / Ciudad del cliente",
                td1Stored: "No — solo en RAM durante la sesión",
                td2Data: "Teléfono y e-mail del cliente",
                td2Stored: "No — transmitido P2P, nunca escrito en disco",
                td3Data: "Dirección temporal (hotel/Airbnb)",
                td3Stored: "No — mismo canal P2P",
                td4Data: "Código de sesión (6 dígitos)",
                td4Stored: "No — expira al cerrar la pestaña",
                td5Data: "Nombre de la agencia (licencia)",
                td5Stored: "Sí — en KV (no es dato personal)",
                td6Data: "Fecha de expiración de la licencia",
                td6Stored: "Sí — en KV (no es dato personal)",
                td7Data: "IP + fecha aceptación condiciones",
                td7Stored: "Sí — en KV (registro legal de activación)",
                
                h4Title: "4. Garantías técnicas clave",
                h4_1Title: "4.1 Sin base de datos de clientes",
                h4_1P: "Las funciones serverless únicamente acceden a metadatos de licencia. El código fuente ha sido auditado y no contiene ninguna instrucción de escritura de datos personales.",
                h4_2Title: "4.2 Cifrado extremo a extremo",
                h4_2P: "WebRTC utiliza DTLS para el plano de datos y SRTP para el canal de mensajes. Ningún nodo intermedio puede leer el contenido.",
                h4_3Title: "4.3 Efímero por diseño",
                h4_3P: "El código de sesión se destruye al cerrar la pestaña. No se persiste en cookies ni storage.",
                h4_4Title: "4.4 Sin logs en servidor",
                h4_4P: "Las cabeceras HTTP incluyen Cache-Control: no-store, impidiendo almacenamiento en caché. Los Workers no registran el cuerpo de las peticiones P2P.",
                
                h5Title: "5. Ciclo de vida de un dato personal",
                h5L1: "▸ El cliente teclea su e-mail (campo HTML).",
                h5L2: "▸ Al pulsar enviar, el script empaqueta los datos en memoria RAM.",
                h5L3: "▸ El objeto se envía mediante API WebRTC cifrada DTLS directamente al asesor.",
                h5L4: "▸ El asesor recibe el dato y lo muestra en pantalla.",
                h5L5: "▸ En ningún momento se realiza una llamada HTTP POST a servidores con estos datos.",
                h5L6: "▸ Al cerrar la pestaña, el objeto desaparece de la RAM. No queda ninguna copia.",
                
                h6Title: "6. Conclusión",
                h6L1: "Cumple el principio de minimización del RGPD (Art. 5.1.c).",
                h6L2: "No existe base de datos de clientes. Los datos nunca tocan un servidor.",
                h6L3: "Canal P2P cifrado extremo a extremo por estándar.",
                h6L4: "El almacenamiento persistente (KV) contiene exclusivamente datos de licencia de la agencia.",
                
                h7Title: "7. Referencias de código auditables",
                h7L1: "Verificación de licencia — no lee ni escribe datos personales",
                h7L2: "Gestión de licencias — solo escribe metadatos en KV",
                h7L3: "Registra IP + fecha de aceptación CGU",
                h7L4: "Genera credenciales TURN efímeras",
                h7L5: "Aviso legal visible",
                
                docFooter: "Guilhem Normand — 2026 — Documento confidencial",
                footerRights: "© 2026. Todos los derechos reservados."
            },
            fr: {
                navHome: "Retour à l'accueil",
                pageTitle: "Note Technique - Sécurité",
                docTitle: "NOTE TECHNIQUE",
                docSubtitle: "Confidentialité et non-stockage des données personnelles",
                metaProduct: "Produit: Client Form",
                metaVersion: "Version: 2026",
                metaAuthor: "Auteur: Guilhem Normand",
                
                h1Title: "1. Résumé exécutif",
                h1P1: "Cette note répond à la question : « Comment l'application garantit-elle que les informations client ne sont sauvegardées nulle part ? »",
                h1P2: "La réponse est structurelle : l'application agit comme un miroir numérique. Les données saisies par le client se reflètent en temps réel sur l'écran du conseiller, sans passer par aucun serveur ni base de données. Dès la fermeture de la session, les données disparaissent.",
                
                h2Title: "2. Architecture : fonctionnement du miroir",
                h2P1: "La transmission s'effectue via WebRTC (Web Real-Time Communication), une technologie de connexion directe P2P standardisée par le W3C.",
                diagClient: "Appareil client",
                diagClientSub: "Saisit ses données",
                diagChannel: "Canal WebRTC P2P",
                diagChannelSub: "Chiffrement de bout en bout",
                diagAgent: "Écran conseiller",
                diagAgentSub: "Affiche en temps réel",
                h2P2: "Aucun serveur intermédiaire ne touche les données. Le serveur de signalisation agit uniquement comme un annuaire téléphonique pour établir le canal, puis disparaît.",
                
                h3Title: "3. Quelles données sont stockées ?",
                thData: "Donnée",
                thStored: "Est-elle stockée ?",
                td1Data: "Adresse / CP / Ville du client",
                td1Stored: "Non — uniquement en RAM",
                td2Data: "Téléphone et e-mail",
                td2Stored: "Non — transmission P2P uniquement",
                td3Data: "Adresse temporaire (hôtel/Airbnb)",
                td3Stored: "Non — même canal P2P",
                td4Data: "Code de session (6 chiffres)",
                td4Stored: "Non — expire à la fermeture",
                td5Data: "Nom de l'agence (licence)",
                td5Stored: "Oui — en KV (pas une donnée personnelle)",
                td6Data: "Date d'expiration de la licence",
                td6Stored: "Oui — en KV (pas une donnée personnelle)",
                td7Data: "IP + date d'acceptation des CGU",
                td7Stored: "Oui — en KV (registre légal)",
                
                h4Title: "4. Garanties techniques",
                h4_1Title: "4.1 Aucune base de données clients",
                h4_1P: "Le code source a été audité et ne contient aucune instruction d'écriture de données personnelles. Les fonctions accèdent uniquement aux métadonnées des licences.",
                h4_2Title: "4.2 Chiffrement de bout en bout",
                h4_2P: "WebRTC utilise DTLS pour les données. Aucun noeud intermédiaire ne peut lire le contenu.",
                h4_3Title: "4.3 Éphémère par design",
                h4_3P: "Le code de session est détruit à la fermeture. Aucune persistance dans les cookies ou le stockage local.",
                h4_4Title: "4.4 Zéro log serveur",
                h4_4P: "Les requêtes P2P sont directes. Les en-têtes HTTP bloquent la mise en cache (Cache-Control: no-store).",
                
                h5Title: "5. Cycle de vie d'une donnée",
                h5L1: "▸ Le client tape son e-mail.",
                h5L2: "▸ Le script empaquette les données en RAM.",
                h5L3: "▸ L'objet est envoyé via WebRTC chiffré directement au conseiller.",
                h5L4: "▸ Le conseiller reçoit et affiche la donnée.",
                h5L5: "▸ Aucun appel HTTP POST n'est fait avec ces données.",
                h5L6: "▸ À la fermeture, la RAM est vidée. Aucune copie n'existe.",
                
                h6Title: "6. Conclusion",
                h6L1: "Respecte le principe de minimisation du RGPD (Art. 5.1.c).",
                h6L2: "Aucune base de données clients. Les données ne touchent pas de serveur.",
                h6L3: "Canal P2P chiffré de bout en bout.",
                h6L4: "Stockage KV restreint aux données de licences agence.",
                
                h7Title: "7. Références de code",
                h7L1: "Vérification de licence — ne lit/écrit aucune donnée client",
                h7L2: "Gestion licences — écrit uniquement les métadonnées KV",
                h7L3: "Enregistre IP + date d'acceptation",
                h7L4: "Génère des identifiants TURN éphémères",
                h7L5: "Mention légale affichée",
                
                docFooter: "Guilhem Normand — 2026 — Document confidentiel",
                footerRights: "© 2026. Tous droits réservés."
            },
            en: {
                navHome: "Back to Home",
                pageTitle: "Technical Note - Security",
                docTitle: "TECHNICAL NOTE",
                docSubtitle: "Confidentiality and non-storage of personal data",
                metaProduct: "Product: Client Form",
                metaVersion: "Version: 2026",
                metaAuthor: "Author: Guilhem Normand",
                
                h1Title: "1. Executive Summary",
                h1P1: "This note addresses the question: «How does the application guarantee that customer information is not saved anywhere?»",
                h1P2: "The answer is structural: the application acts as a digital mirror. The data typed by the customer is reflected in real-time on the agent's screen, without passing through any server or database. Once the session is closed, the data disappears.",
                
                h2Title: "2. Architecture: how the mirror works",
                h2P1: "Data transmission is done via WebRTC (Web Real-Time Communication), a direct P2P connection technology standardized by the W3C.",
                diagClient: "Client device",
                diagClientSub: "Enters data",
                diagChannel: "P2P WebRTC Channel",
                diagChannelSub: "End-to-end encrypted",
                diagAgent: "Agent screen",
                diagAgentSub: "Shows data in real-time",
                h2P2: "No intermediate server touches the personal data. The signaling server acts only as a 'phonebook' to establish the channel, then vanishes.",
                
                h3Title: "3. What data is stored?",
                thData: "Data",
                thStored: "Is it stored?",
                td1Data: "Customer Address / ZIP / City",
                td1Stored: "No — only in RAM during session",
                td2Data: "Customer Phone and E-mail",
                td2Stored: "No — P2P transmission only",
                td3Data: "Temporary address (Hotel/Airbnb)",
                td3Stored: "No — same P2P channel",
                td4Data: "Session code (6 digits)",
                td4Stored: "No — expires on close",
                td5Data: "Agency name (license)",
                td5Stored: "Yes — in KV (not personal data)",
                td6Data: "License expiration date",
                td6Stored: "Yes — in KV (not personal data)",
                td7Data: "IP + terms acceptance date",
                td7Stored: "Yes — in KV (legal record)",
                
                h4Title: "4. Key technical guarantees",
                h4_1Title: "4.1 No customer database",
                h4_1P: "The source code has been audited and contains no instructions to write personal data. Functions only access license metadata.",
                h4_2Title: "4.2 End-to-end encryption",
                h4_2P: "WebRTC uses DTLS. No intermediate node can read the content.",
                h4_3Title: "4.3 Ephemeral by design",
                h4_3P: "The session code is destroyed upon closing. No persistence in cookies or local storage.",
                h4_4Title: "4.4 Zero server logs",
                h4_4P: "P2P requests are direct. HTTP headers block caching (Cache-Control: no-store).",
                
                h5Title: "5. Lifecycle of personal data",
                h5L1: "▸ Customer types their e-mail.",
                h5L2: "▸ Script packages data in RAM.",
                h5L3: "▸ Object is sent via encrypted WebRTC directly to the agent.",
                h5L4: "▸ Agent receives and displays data.",
                h5L5: "▸ No HTTP POST call is made with these data.",
                h5L6: "▸ Upon closing, RAM is cleared. No copy remains.",
                
                h6Title: "6. Conclusion",
                h6L1: "Complies with GDPR minimization principle (Art. 5.1.c).",
                h6L2: "No customer database. Data never touches a server.",
                h6L3: "P2P channel is end-to-end encrypted.",
                h6L4: "KV storage is restricted to agency license data.",
                
                h7Title: "7. Auditable code references",
                h7L1: "License verification — reads/writes no personal data",
                h7L2: "License management — writes only metadata to KV",
                h7L3: "Logs IP + acceptance date",
                h7L4: "Generates ephemeral TURN credentials",
                h7L5: "Visible legal notice",
                
                docFooter: "Guilhem Normand — 2026 — Confidential Document",
                footerRights: "© 2026. All rights reserved."
            },
            it: {
                navHome: "Torna alla Home",
                pageTitle: "Nota Tecnica - Sicurezza",
                docTitle: "NOTA TECNICA",
                docSubtitle: "Riservatezza e non conservazione dei dati personali",
                metaProduct: "Prodotto: Client Form",
                metaVersion: "Versione: 2026",
                metaAuthor: "Autore: Guilhem Normand",
                h1Title: "1. Sintesi",
                h1P1: "Questa nota risponde alla domanda: «Come garantisce l'applicazione che le informazioni non vengano salvate?»",
                h1P2: "L'applicazione agisce come uno specchio digitale. I dati inseriti si riflettono in tempo reale senza passare da server. Alla chiusura, scompaiono.",
                h2Title: "2. Architettura",
                h2P1: "La trasmissione avviene via WebRTC, connessione P2P diretta.",
                diagClient: "Dispositivo cliente",
                diagClientSub: "Inserisce i dati",
                diagChannel: "Canale WebRTC P2P",
                diagChannelSub: "Crittografia end-to-end",
                diagAgent: "Schermo agente",
                diagAgentSub: "Mostra dati in tempo reale",
                h2P2: "Nessun server intermedio tocca i dati. Il server di segnalazione serve solo per stabilire la connessione.",
                h3Title: "3. Quali dati vengono salvati?",
                thData: "Dato",
                thStored: "Salvato?",
                td1Data: "Indirizzo cliente",
                td1Stored: "No — solo in RAM",
                td2Data: "Telefono / Email",
                td2Stored: "No — solo P2P",
                td3Data: "Indirizzo temporaneo",
                td3Stored: "No",
                td4Data: "Codice sessione",
                td4Stored: "No",
                td5Data: "Nome agenzia",
                td5Stored: "Sì — in KV",
                td6Data: "Scadenza licenza",
                td6Stored: "Sì — in KV",
                td7Data: "IP + accettazione termini",
                td7Stored: "Sì — in KV (registro legale)",
                h4Title: "4. Garanzie tecniche",
                h4_1Title: "4.1 Nessun database clienti",
                h4_1P: "Il codice non contiene istruzioni di scrittura di dati personali.",
                h4_2Title: "4.2 Crittografia E2E",
                h4_2P: "Nessun nodo intermedio può leggere il contenuto.",
                h4_3Title: "4.3 Effimero",
                h4_3P: "Nessun dato persistente in cookie o storage locale.",
                h4_4Title: "4.4 Zero log",
                h4_4P: "Nessuna cache HTTP, nessun log P2P.",
                h5Title: "5. Ciclo di vita dei dati",
                h5L1: "▸ Il cliente digita i dati.",
                h5L2: "▸ I dati vanno in RAM.",
                h5L3: "▸ Invio diretto P2P criptato.",
                h5L4: "▸ L'agente visualizza i dati.",
                h5L5: "▸ Nessuna chiamata POST a server esterni.",
                h5L6: "▸ Alla chiusura, la RAM si svuota.",
                h6Title: "6. Conclusione",
                h6L1: "Conforme al principio di minimizzazione GDPR.",
                h6L2: "Zero database. Zero salvataggio.",
                h6L3: "Canale P2P crittografato.",
                h6L4: "Solo dati agenzia nel database KV.",
                h7Title: "7. Riferimenti al codice",
                h7L1: "Verifica licenza",
                h7L2: "Gestione licenze",
                h7L3: "Log IP legali",
                h7L4: "Credenziali TURN",
                h7L5: "Avviso legale",
                docFooter: "Guilhem Normand — 2026 — Documento Riservato",
                footerRights: "© 2026. Tutti i diritti riservati."
            },
            pt: {
                navHome: "Voltar",
                pageTitle: "Nota Técnica - Segurança",
                docTitle: "NOTA TÉCNICA",
                docSubtitle: "Confidencialidade e não armazenamento de dados",
                metaProduct: "Produto: Client Form",
                metaVersion: "Versão: 2026",
                metaAuthor: "Autor: Guilhem Normand",
                h1Title: "1. Resumo",
                h1P1: "Como o aplicativo garante que os dados não são salvos?",
                h1P2: "Funciona como um espelho digital P2P. Fecha a sessão, os dados somem.",
                h2Title: "2. Arquitetura",
                h2P1: "Transmissão WebRTC direta.",
                diagClient: "Cliente",
                diagClientSub: "Digita dados",
                diagChannel: "Canal P2P",
                diagChannelSub: "Criptografia E2E",
                diagAgent: "Agente",
                diagAgentSub: "Vê em tempo real",
                h2P2: "Nenhum servidor intermediário lê os dados.",
                h3Title: "3. O que é salvo?",
                thData: "Dado",
                thStored: "Salvo?",
                td1Data: "Endereço cliente",
                td1Stored: "Não",
                td2Data: "Telefone / Email",
                td2Stored: "Não",
                td3Data: "Endereço temporário",
                td3Stored: "Não",
                td4Data: "Código de sessão",
                td4Stored: "Não",
                td5Data: "Nome agência",
                td5Stored: "Sim — KV",
                td6Data: "Validade licença",
                td6Stored: "Sim — KV",
                td7Data: "IP + aceite",
                td7Stored: "Sim — KV (legal)",
                h4Title: "4. Garantias",
                h4_1Title: "4.1 Sem BD de clientes",
                h4_1P: "Código auditado.",
                h4_2Title: "4.2 Criptografia E2E",
                h4_2P: "Nós intermediários não leem o conteúdo.",
                h4_3Title: "4.3 Efêmero",
                h4_3P: "Sem cookies.",
                h4_4Title: "4.4 Zero logs",
                h4_4P: "Sem logs HTTP/P2P.",
                h5Title: "5. Ciclo de vida",
                h5L1: "▸ Cliente digita.",
                h5L2: "▸ Dados na RAM.",
                h5L3: "▸ Envio WebRTC.",
                h5L4: "▸ Agente vê.",
                h5L5: "▸ Sem POST externo.",
                h5L6: "▸ RAM limpa ao fechar.",
                h6Title: "6. Conclusão",
                h6L1: "Em conformidade com RGPD.",
                h6L2: "Zero BD.",
                h6L3: "Canal P2P criptografado.",
                h6L4: "Apenas dados de licença salvos.",
                h7Title: "7. Código",
                h7L1: "Verificação licença",
                h7L2: "Gestão licenças",
                h7L3: "Registro legal IP",
                h7L4: "TURN effêmero",
                h7L5: "Aviso legal",
                docFooter: "Guilhem Normand — 2026 — Confidencial",
                footerRights: "© 2026."
            },
            de: {
                navHome: "Zurück",
                pageTitle: "Technische Notiz - Sicherheit",
                docTitle: "TECHNISCHE NOTIZ",
                docSubtitle: "Datenschutz und Nicht-Speicherung von Daten",
                metaProduct: "Produkt: Client Form",
                metaVersion: "Version: 2026",
                metaAuthor: "Autor: Guilhem Normand",
                h1Title: "1. Zusammenfassung",
                h1P1: "Wie garantieren wir, dass keine Daten gespeichert werden?",
                h1P2: "P2P Digitaler Spiegel. Nach der Sitzung werden alle Daten gelöscht.",
                h2Title: "2. Architektur",
                h2P1: "WebRTC direkte Verbindung.",
                diagClient: "Kunde",
                diagClientSub: "Gibt Daten ein",
                diagChannel: "P2P Kanal",
                diagChannelSub: "End-to-End verschlüsselt",
                diagAgent: "Agent",
                diagAgentSub: "Sieht Daten in Echtzeit",
                h2P2: "Kein Zwischenserver liest Daten.",
                h3Title: "3. Was wird gespeichert?",
                thData: "Daten",
                thStored: "Gespeichert?",
                td1Data: "Kundenadresse",
                td1Stored: "Nein",
                td2Data: "Telefon / E-Mail",
                td2Stored: "Nein",
                td3Data: "Temporäre Adresse",
                td3Stored: "Nein",
                td4Data: "Sitzungscode",
                td4Stored: "Nein",
                td5Data: "Agenturname",
                td5Stored: "Ja — KV",
                td6Data: "Lizenzablauf",
                td6Stored: "Ja — KV",
                td7Data: "IP + Akzeptanz",
                td7Stored: "Ja — KV (Legal)",
                h4Title: "4. Garantien",
                h4_1Title: "4.1 Keine Kundendatenbank",
                h4_1P: "Geprüfter Code.",
                h4_2Title: "4.2 E2E Verschlüsselung",
                h4_2P: "Keine Zwischenknoten.",
                h4_3Title: "4.3 Ephemer",
                h4_3P: "Keine Cookies.",
                h4_4Title: "4.4 Keine Logs",
                h4_4P: "Keine HTTP/P2P Logs.",
                h5Title: "5. Lebenszyklus",
                h5L1: "▸ Kunde tippt.",
                h5L2: "▸ Daten im RAM.",
                h5L3: "▸ WebRTC Senden.",
                h5L4: "▸ Agent sieht es.",
                h5L5: "▸ Kein POST.",
                h5L6: "▸ RAM wird gelöscht.",
                h6Title: "6. Fazit",
                h6L1: "DSGVO-konform.",
                h6L2: "Null DB.",
                h6L3: "P2P Kanal verschlüsselt.",
                h6L4: "Nur Lizenzdaten gespeichert.",
                h7Title: "7. Code",
                h7L1: "Lizenzprüfung",
                h7L2: "Lizenzverwaltung",
                h7L3: "IP Log",
                h7L4: "TURN",
                h7L5: "Impressum",
                docFooter: "Guilhem Normand — 2026 — Vertraulich",
                footerRights: "© 2026."
            },
            nl: {
                navHome: "Terug",
                pageTitle: "Technische Notitie - Veiligheid",
                docTitle: "TECHNISCHE NOTITIE",
                docSubtitle: "Privacy en niet-opslag van gegevens",
                metaProduct: "Product: Client Form",
                metaVersion: "Versie: 2026",
                metaAuthor: "Auteur: Guilhem Normand",
                h1Title: "1. Samenvatting",
                h1P1: "Hoe garanderen we dat er geen gegevens worden opgeslagen?",
                h1P2: "P2P Digitale spiegel. Na de sessie worden alle gegevens verwijderd.",
                h2Title: "2. Architectuur",
                h2P1: "WebRTC directe verbinding.",
                diagClient: "Klant",
                diagClientSub: "Voert gegevens in",
                diagChannel: "P2P Kanaal",
                diagChannelSub: "End-to-End versleuteld",
                diagAgent: "Agent",
                diagAgentSub: "Ziet gegevens live",
                h2P2: "Geen tussenserver leest gegevens.",
                h3Title: "3. Wat wordt opgeslagen?",
                thData: "Gegevens",
                thStored: "Opgeslagen?",
                td1Data: "Adres klant",
                td1Stored: "Nee",
                td2Data: "Telefoon / E-mail",
                td2Stored: "Nee",
                td3Data: "Tijdelijk adres",
                td3Stored: "Nee",
                td4Data: "Sessie code",
                td4Stored: "Nee",
                td5Data: "Naam agentschap",
                td5Stored: "Ja — KV",
                td6Data: "Licentie verloopdatum",
                td6Stored: "Ja — KV",
                td7Data: "IP + Acceptatie",
                td7Stored: "Ja — KV (Juridisch)",
                h4Title: "4. Garanties",
                h4_1Title: "4.1 Geen klantendatabase",
                h4_1P: "Gecontroleerde code.",
                h4_2Title: "4.2 E2E Versleuteling",
                h4_2P: "Geen tussenknooppunten.",
                h4_3Title: "4.3 Vluchtig",
                h4_3P: "Geen cookies.",
                h4_4Title: "4.4 Geen logs",
                h4_4P: "Geen HTTP/P2P logs.",
                h5Title: "5. Levenscyclus",
                h5L1: "▸ Klant typt.",
                h5L2: "▸ Gegevens in RAM.",
                h5L3: "▸ WebRTC Verzenden.",
                h5L4: "▸ Agent ziet het.",
                h5L5: "▸ Geen POST.",
                h5L6: "▸ RAM wordt gewist.",
                h6Title: "6. Conclusie",
                h6L1: "AVG-conform.",
                h6L2: "Nul DB.",
                h6L3: "P2P kanaal versleuteld.",
                h6L4: "Alleen licentiegegevens opgeslagen.",
                h7Title: "7. Code",
                h7L1: "Licentie controle",
                h7L2: "Licentie beheer",
                h7L3: "IP Log",
                h7L4: "TURN",
                h7L5: "Wettelijke kennisgeving",
                docFooter: "Guilhem Normand — 2026 — Vertrouwelijk",
                footerRights: "© 2026."
            }
        };

        const updateLanguage = (lang) => {
            const dict = i18n[lang] || i18n['es'];
            document.querySelectorAll('[data-i18n]').forEach(el => {
                const key = el.getAttribute('data-i18n');
                if (dict[key]) {
                    el.textContent = dict[key];
                }
            });
            document.documentElement.lang = lang;
        };

        const langSelect = document.getElementById('languageSelect');
        const langDisplay = document.getElementById('langDisplay');
        if (langSelect && langDisplay) {
            langSelect.addEventListener('change', (e) => {
                const text = e.target.options[e.target.selectedIndex].text;
                const lang = e.target.value;
                langDisplay.textContent = text;
                updateLanguage(lang);
            });
        }

        // Auto-detect language from browser
        const supportedLangs = ['fr','en','es','it','pt','de','nl'];
        const browserLang = (navigator.language || 'en').slice(0, 2).toLowerCase();
        const detectedLang = supportedLangs.includes(browserLang) ? browserLang : 'en';
        if (langSelect) {
            langSelect.value = detectedLang;
            if (langDisplay) langDisplay.textContent = langSelect.options[langSelect.selectedIndex].text;
        }
        updateLanguage(detectedLang);

        // Animations and scroll reveal (similar to main page)
        const revealElements = document.querySelectorAll('.reveal');
        const revealObserver = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('active');
                }
            });
        }, { threshold: 0.1 });

        revealElements.forEach(el => revealObserver.observe(el));
        
        // Ambient Cursor Glow
        const ambientGlow = document.createElement('div');
        ambientGlow.className = 'ambient-cursor-glow';
        document.body.appendChild(ambientGlow);

        document.addEventListener('mousemove', (e) => {
            ambientGlow.style.transform = `translate(${e.clientX}px, ${e.clientY}px)`;
        });
        
    });
})();
